sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g pm2
script:
  - npm run build
  - npm run build:server
